export type GiftPackItem = {
  name: string;
  qty: string;
};

/** Readable pack contents by product slug (from gift-box flyers). */
export const GIFT_PACK_CONTENTS: Record<string, GiftPackItem[]> = {
  "amazing-gift-pack": [
    { name: "Gold Lakshmi", qty: "1 Pkt" },
    { name: "3 1/2 Lakshmi", qty: "1 Pkt" },
    { name: "2 3/4 Kuruvi", qty: "1 Pkt" },
    { name: "Parrot", qty: "1 Pkt" },
    { name: "28 Saramwala", qty: "1 Pkt" },
    { name: "Bijili", qty: "1 Pkt" },
    { name: "Flower Pot Big", qty: "1 Pkt" },
    { name: "Disco Wheel", qty: "1 Piece" },
    { name: "Photo Flash", qty: "1 Piece" },
    { name: "Shower", qty: "1 Piece" },
    { name: '4" Lakshmi', qty: "1 Pkt" },
    { name: "Military Boom", qty: "1 Piece" },
    { name: "Snake Tablet", qty: "1 Box" },
    { name: "Roll Cap", qty: "1 Pkt" },
    { name: "Twinkling Star", qty: "1 Box" },
    { name: "Paper Vedi", qty: "1 Piece" },
    { name: "Colour Kotti", qty: "1 Piece" },
    { name: "Electric Sparkler", qty: "1 Box" },
    { name: "Selfie Stick", qty: "1 Piece" },
    { name: "Sparkler", qty: "1 Box" },
    { name: "Ring Cap", qty: "1 Pkt" },
    { name: "Tube Vedi", qty: "1 Box" },
    { name: "Colour Sparkler", qty: "1 Box" },
    { name: "Pop Pop", qty: "1 Box" },
    { name: "Ground Chakra Big", qty: "1 Box" },
    { name: "Electric Sparkler", qty: "1 Box" },
    { name: "Match Green", qty: "1 Box" },
    { name: "Match Silver", qty: "1 Box" },
    { name: "Match Red", qty: "1 Box" },
    { name: "Electric Stone", qty: "1 Box" },
  ],
  "golden-gift-pack": [
    { name: "Bijili", qty: "1 Pkt" },
    { name: "Gold Lakshmi", qty: "1 Pkt" },
    { name: '4" Lakshmi', qty: "1 Pkt" },
    { name: '4" Joker', qty: "1 Pkt" },
    { name: '3 1/2" Lakshmi', qty: "1 Pkt" },
    { name: '3" Parrot', qty: "1 Pkt" },
    { name: '2 3/4" Kuruvi', qty: "1 Pkt" },
    { name: "Paper Boom", qty: "1 Piece" },
    { name: "Valangaiman Vedi", qty: "2 Piece" },
    { name: "Military Boom", qty: "1 Piece" },
    { name: '28" Saram', qty: "1 Pkt" },
    { name: "Gun Pop", qty: "1 Box" },
    { name: "Angrybird Blast", qty: "1 Box" },
    { name: "Tube Blast", qty: "1 Box" },
    { name: "Snake Blast", qty: "1 Box" },
    { name: "7cm Sparkler", qty: "1 Box" },
    { name: "7cm Electric", qty: "1 Box" },
    { name: "Ring Cap", qty: "1 Pkt" },
    { name: "Match Red", qty: "1 Box" },
    { name: "Match Silver", qty: "1 Box" },
    { name: "Match Gold Star", qty: "1 Box" },
    { name: "7 Shot", qty: "1 Piece" },
    { name: "Pops Big", qty: "1 Piece" },
    { name: "Selfie Stick", qty: "1 Piece" },
    { name: "Electric Stone", qty: "1 Box" },
    { name: "Green Sparkler", qty: "1 Box" },
    { name: "Crackling", qty: "1 Box" },
    { name: "Colour Sparkler", qty: "1 Box" },
    { name: "10 cm Sparkler", qty: "1 Box" },
    { name: "Ground Chakra Big", qty: "1 Box" },
    { name: "Flower Pot Big", qty: "1 Box" },
    { name: "Twinkling Star", qty: "1 Box" },
    { name: "Roll Cap", qty: "1 Piece" },
    { name: "Photo Flash", qty: "1 Piece" },
    { name: "Disco Wheel", qty: "1 Piece" },
    { name: "Golden Asarafi", qty: "1 Piece" },
    { name: "Colour Koti", qty: "1 Piece" },
    { name: "Colour Bird", qty: "1 Piece" },
    { name: "Colour Smoke", qty: "1 Piece" },
    { name: "Pops Small", qty: "1 Piece" },
  ],
  "mayur-gift-box": [
    { name: "Bijili", qty: "1 Pkt" },
    { name: "Flower Pot Big", qty: "1 Pkt" },
    { name: "Ground Chakra Big", qty: "1 Pkt" },
    { name: "Disco Wheel", qty: "1 Piece" },
    { name: "Rider Red", qty: "1 Piece" },
    { name: "Photo Flash", qty: "1 Piece" },
    { name: "Rider Green", qty: "1 Piece" },
    { name: "28 Saram", qty: "1 Pkt" },
    { name: "Rider Star", qty: "1 Piece" },
    { name: "1 1/2 Twinkling Star", qty: "1 Pkt" },
    { name: "Roll Cap", qty: "1 Pkt" },
    { name: "Colour Koti", qty: "1 Piece" },
    { name: "3 1/2 Lakshmi", qty: "1 Pkt" },
    { name: "2 3/4 Kuruvi", qty: "1 Pkt" },
    { name: "555 Bomb", qty: "1 Piece" },
    { name: "7 cm Crackling", qty: "1 Box" },
    { name: "Jee Boom Baa", qty: "1 Box" },
    { name: "7 cm Colour", qty: "1 Box" },
    { name: "Paper Vedi", qty: "1 Piece" },
    { name: "Electric Stone", qty: "1 Box" },
  ],
};

export function getGiftPackContents(slug: string): GiftPackItem[] | null {
  return GIFT_PACK_CONTENTS[slug] ?? null;
}
