export type GiftPackItem = {
  name: string;
  qty: string;
};

/** Readable pack contents by product slug (from gift-box flyers). */
export const GIFT_PACK_CONTENTS: Record<string, GiftPackItem[]> = {
  "16-items-gift-pack": [
    { name: "Bijli", qty: "1 Pkt" },
    { name: "3 1/2 Lakshmi", qty: "1 Pkt" },
    { name: "2 3/4 Kuruvi", qty: "1 Pkt" },
    { name: "28 Wala", qty: "1 Pkt" },
    { name: "Paper Vedi", qty: "1 Pcs" },
    { name: "Minor Star", qty: "1 Box" },
    { name: "Electric Stone", qty: "1 Box" },
    { name: "Disco Wheel", qty: "1 Pcs" },
    { name: "Auto Bomb", qty: "1 Box" },
    { name: "Colour Kotti", qty: "1 Box" },
    { name: "Rider Star", qty: "1 Box" },
    { name: "2 1/4 Kuruvi", qty: "1 Pkt" },
    { name: "Snake Tablet", qty: "1 Box" },
    { name: "7cm Sparkler", qty: "1 Box" },
    { name: "10cm Electric", qty: "1 Box" },
    { name: "Colour Changing Bird", qty: "1 Piece" },
  ],
  "21-items-gift-pack": [
    { name: "3 1/2 Lakshmi", qty: "1 Pkt" },
    { name: "3/4 Kuruvi", qty: "1 Pkt" },
    { name: "2 3/4 Kuruvi", qty: "1 Pkt" },
    { name: "Military Boom", qty: "1 Pkt" },
    { name: "3 3/4 Lakshmi", qty: "1 Pkt" },
    { name: "Match Red", qty: "1 Pcs" },
    { name: "Match Green", qty: "1 Box" },
    { name: "Roll Cap", qty: "1 Box" },
    { name: "Photo Flash", qty: "1 Pkt" },
    { name: "Selfie Stick", qty: "1 Pcs" },
    { name: "Twinkling Star", qty: "1 Box" },
    { name: "Disco Wheel", qty: "1 Pcs" },
    { name: "Flowerpot", qty: "1 Box" },
    { name: "G. Chakra", qty: "1 Box" },
    { name: "Match Yellow", qty: "1 Box" },
    { name: "Fancy Pen", qty: "1 Pcs" },
    { name: "Colour Changing Bird", qty: "1 Pcs" },
    { name: "7cm Sparkler", qty: "1 Box" },
    { name: "Electric Stone", qty: "1 Box" },
    { name: "10cm Colour", qty: "1 Box" },
    { name: "28 Wala", qty: "1 Pkt" },
  ],
  "25-items-gift-pack": [
    { name: "Bijli", qty: "1 Pkt" },
    { name: "3 1/2 Lakshmi", qty: "1 Pkt" },
    { name: "2 3/4 Kuruvi", qty: "1 Pkt" },
    { name: "28 Wala", qty: "1 Pkt" },
    { name: "Parrot", qty: "1 Pkt" },
    { name: "Disco Wheel", qty: "1 Piece" },
    { name: "Electric Sparkle", qty: "1 Box" },
    { name: "Photo Flash", qty: "1 Piece" },
    { name: "Flower Pot", qty: "1 Box" },
    { name: "7cm Sparkle", qty: "1 Box" },
    { name: "Military Boom", qty: "1 Piece" },
    { name: "Ring Caps", qty: "1 Pkt" },
    { name: "10cm Sparkle", qty: "1 Box" },
    { name: "Snake Tablet", qty: "1 Box" },
    { name: "Twinkling Star", qty: "1 Box" },
    { name: "10cm Electric", qty: "1 Box" },
    { name: "Colour Changing Bird", qty: "1 Piece" },
    { name: "Ashrafi", qty: "1 Piece" },
    { name: "Match Blue", qty: "1 Box" },
    { name: "Grand Chakra", qty: "1 Box" },
    { name: "Selfie Stick", qty: "1 Piece" },
    { name: "Match Yellow", qty: "1 Box" },
    { name: "Pops Big", qty: "1 Box" },
    { name: "Match Pink", qty: "1 Box" },
    { name: "Electric Stone", qty: "1 Box" },
  ],
  "30-items-gift-pack": [
    { name: "Bijili", qty: "1 Pkt" },
    { name: "28 Saramwala", qty: "1 Pkt" },
    { name: "2 3/4 Kuruvi", qty: "1 Pkt" },
    { name: "3 1/2 Lakshmi", qty: "1 Pkt" },
    { name: "Paper Vedi", qty: "1 Pcs" },
    { name: "Lakshmi Paper Vedi", qty: "1 Pcs" },
    { name: "Minor Red", qty: "1 Box" },
    { name: "Minor Star", qty: "1 Box" },
    { name: "Electric Stone", qty: "1 Box" },
    { name: "Photo Flash", qty: "1 Pcs" },
    { name: "Disco Wheel", qty: "1 Pcs" },
    { name: "Auto Bomb", qty: "1 Box" },
    { name: "Colour Koti", qty: "1 Pkt" },
    { name: "Rider Star", qty: "1 Pkt" },
    { name: "2 3/4 Kuruvi", qty: "1 Pkt" },
    { name: "Snake Tablet", qty: "1 Box" },
    { name: "7cm Sparkler", qty: "1 Box" },
    { name: "7cm Colour", qty: "1 Box" },
    { name: "15cm Electric", qty: "1 Box" },
    { name: "12cm Electric", qty: "1 Box" },
    { name: "Chakra Big", qty: "1 Box" },
    { name: "Ground Chakkar Special", qty: "3 Pcs" },
    { name: "Flower Pot Big", qty: "1 Box" },
    { name: '4" Twinkling Star', qty: "3 Pcs" },
    { name: '1 1/2" Twinkling Star', qty: "1 Box" },
    { name: "Roll Cap", qty: "1 Pkt" },
    { name: "Jeeboom Ba", qty: "1 Box" },
    { name: "Pops", qty: "1 Pcs" },
    { name: '6" Colour Vedi', qty: "1 Pcs" },
    { name: "Colour Stone", qty: "1 Box" },
  ],
};

export function getGiftPackContents(slug: string): GiftPackItem[] | null {
  return GIFT_PACK_CONTENTS[slug] ?? null;
}
