/** Re-export Prisma domain types for existing `@/lib/db/types` imports. */
export type {
  AdminUser,
  Category,
  Product,
  Order,
  OrderItem,
  OrderStatusHistory,
  Enquiry,
  SiteVisit,
  EmailSettings,
  EmailLog,
  AdminNotification,
  AdminPushLog,
  BackupSettings,
  DbBackupLog,
  ArchiveSettings,
  ArchiveLog,
  SchedulerState,
  AdminDeviceToken,
  FirebaseSettings,
  AuditLog,
  ReportEmailSettings,
  OrderStatus,
  EnquiryStatus,
  UserRole,
  BackupFrequency,
  ReportEmailFrequency,
  ArchiveFrequency,
} from "@prisma/client";
