// Real product pack photos — sourced from velcrackerssivakasi.com (no watermarks).
export const PRODUCT_IMAGES: Record<string, string> = {
  "7 cm Electric Sparklers": "/products/photos/7-cm-electric-sparklers.jpg",
  "7 cm Colour Sparklers": "/products/photos/7-cm-colour-sparklers.jpg",
  "10 cm Electric Sparklers": "/products/photos/10-cm-electric-sparklers.jpg",
  "10 cm Colour Sparklers": "/products/photos/10-cm-colour-sparklers.jpg",
  "15 cm Electric Sparklers": "/products/photos/15-cm-electric-sparklers.jpg",
  "15 cm Green Sparklers": "/products/photos/15-cm-green-sparklers.jpg",
  "15 cm Red Sparklers": "/products/photos/15-cm-red-sparklers.jpg",
  "30 cm Electric Sparklers": "/products/photos/30-cm-electric-sparklers.jpg",
  "30 cm Colour Sparklers": "/products/photos/30-cm-colour-sparklers.jpg",
  "50 cm Electric Sparklers": "/products/photos/50-cm-electric-sparklers.jpg",
  "2\" Fancy": "/products/photos/2in-fancy.jpg",
  "2\" Fancy (3 Pcs)": "/products/photos/2in-fancy-3-pcs.jpg",
  "3½\" Fancy": "/products/photos/3-in-fancy.jpg",
  "3½\" Fancy (1 Piece)": "/products/photos/3-in-fancy-1-piece.jpg",
  "4\" Fancy": "/products/photos/4in-fancy.jpg",
  "4\" Fancy (12 Step)": "/products/photos/4in-fancy-12-step.jpg",
  "30 Shots Multi Colour": "/products/photos/30-shots-multi-colour.jpg",
  "3 Pcs Sky Shot (2\")": "/products/photos/3-pcs-sky-shot-2in.jpg",
  "2\" Pipe (1 Piece)": "/products/photos/2in-pipe-1-piece.jpg",
  "Sky Scrapper": "/products/photos/sky-scrapper.jpg",
  "Green Flash": "/products/photos/green-flash.png",
  "Selfie Stick": "/products/photos/selfie-stick.jpg",
  "Colour Smoke": "/products/photos/colour-smoke.jpg",
  "Rocket Bomb": "/products/photos/rocket-bomb.webp",
  "Whistling Rocket": "/products/photos/whistling-rocket.jpg",
  "Photo Flash": "/products/photos/photo-flash.jpg",
  "7 Shots": "/products/photos/7-shots.png",
  "Mega Peacock (3 Face)": "/products/photos/mega-peacock-3-face.jpg",
  "Bada Peacock (5 Face)": "/products/photos/bada-peacock-5-face.png",
  "Magic Peacock": "/products/photos/magic-peacock.png",
  "Bada Peacock": "/products/photos/bada-peacock.png",
  "Rotate Sparklers": "/products/photos/rotate-sparklers.jpg",
  "Colour Koti": "/products/photos/colour-koti.jpg",
  "Tin Colour Fountain": "/products/photos/tin-colour-fountain.png",
  "Butterfly": "/products/photos/butterfly.jpg",
  "Mega Siren": "/products/photos/mega-siren.jpg",
  "Naya Falls": "/products/photos/naya-falls.jpg",
  "Hitler (¼ Kg)": "/products/photos/hitler-kg.jpg",
  "Hydro Bomb": "/products/photos/hydro-bomb.jpg",
  "Classic Bomb": "/products/photos/classic-bomb.jpg",
  "Digital Bomb": "/products/photos/digital-bomb.jpg",
  "Paper Bomb (¼ Kg)": "/products/photos/paper-bomb-kg.jpg",
  "Paper Bomb (½ Kg)": "/products/photos/paper-bomb-kg.jpg",
  "Paper Bomb (1 Kg)": "/products/photos/paper-bomb-1-kg.jpg",
  "3¼ Lakshmi (1 Packet)": "/products/photos/3-lakshmi-1-packet.jpg",
  "Gold Lakshmi (1 Packet)": "/products/photos/gold-lakshmi-1-packet.jpg",
  "4 DLX Lakshmi": "/products/photos/4-dlx-lakshmi.jpg",
  "Hulk DLX": "/products/photos/hulk-dlx.jpg",
  "5\" Lion (1 Packet)": "/products/photos/5in-lion-1-packet.webp",
  "Red Bijili (100)": "/products/photos/red-bijili-100.jpg",
  "Kaki Ola Vedi (1 Packet)": "/products/photos/kaki-ola-vedi-1-packet.jpg",
  "Jallikattu DLX (1 Packet)": "/products/photos/jallikattu-dlx-1-packet.jpg",
  "Roll Cap": "/products/photos/roll-cap.jpg",
  "Wonder Throw Box": "/products/photos/wonder-throw-box.jpg",
  "Sky Lander (1 Piece)": "/products/photos/sky-lander-1-piece.png",
  "Pop Pop (50 Boxes)": "/products/photos/pop-pop-50-boxes.png",
  "Bidi Blast (10 Boxes)": "/products/photos/bidi-blast-10-boxes.png",
  "Gun with 3 Ring Caps": "/products/photos/gun-with-3-ring-caps.png",
  "Ring Cap (100 Packets)": "/products/photos/ring-cap-100-packets.jpg",
  "Anaconda (10 Boxes)": "/products/photos/anaconda-10-boxes.jpg",
  "28 Wala": "/products/photos/28-wala.jpg",
  "100 Wala": "/products/photos/100-wala.png",
  "200 Wala": "/products/photos/200-wala.png",
  "24 DLX Wala": "/products/photos/24-dlx-wala.png",
  "1000 Wala": "/products/photos/1000-wala.png",
  "2000 Wala": "/products/photos/2000-wala.png",
  "5000 Wala": "/products/photos/5000-wala.png",
  "10000 Wala": "/products/photos/10000-wala.png",
  "10 Crackling": "/products/photos/10-crackling.jpg",
  "2¾ Kuruvi": "/products/photos/2-kuruvi.jpg",
};
