/**
 * Maps SRK catalog product names → Vel Crackers Sivakasi WooCommerce slugs.
 * Source: velcrackerssivakasi.com (no watermark overlays; not jallikattucrackers.in).
 */
export const PRODUCT_VEL_SLUGS: Record<string, string> = {
  "7 cm Electric Sparklers": "7-cm-electric-sparklers",
  "7 cm Colour Sparklers": "7-cm-colour-sparklers",
  "10 cm Electric Sparklers": "10-cm-electric-sparklers",
  "10 cm Colour Sparklers": "10-cm-colour-sparklers",
  "15 cm Electric Sparklers": "15-cm-electric-sparklers",
  "15 cm Green Sparklers": "15-cm-green-sparklers",
  "15 cm Red Sparklers": "15-cm-red-sparklers",
  "30 cm Electric Sparklers": "30-cm-electric-sparklers",
  "30 cm Colour Sparklers": "30-cm-colour-sparklers",
  "50 cm Electric Sparklers": "50-cm-electric-sparklers",

  '2" Fancy': "114-out-7-items-7-colours-1piece",
  '2" Fancy (3 Pcs)': "21-out-7-items-7-colours-3-piece-pack",
  '3½" Fancy': "31-out-10-items-10-colours-1-piece",
  '3½" Fancy (1 Piece)': "31-out-10-items-10-colours-1-piece",
  '4" Fancy': "4-out-2-piece",
  '4" Fancy (12 Step)': "4-out-7-step-7-colours-1-pce",
  "30 Shots Multi Colour": "30-shot-multicolour",
  '3 Pcs Sky Shot (2")': "21-out-7-items-7-colours-3-piece-pack",
  '2" Pipe (1 Piece)': "114-out-7-items-7-colours-1piece",
  "Sky Scrapper": "glittering-pops",
  "Green Flash": "12star-bomb-colour",
  "Selfie Stick": "photo-flash",
  "Colour Smoke": "colour-smoke-peacock",
  "Rocket Bomb": "rockets-bomb",
  "Whistling Rocket": "whistling-rockets",
  "Photo Flash": "photo-flash",
  "7 Shots": "seven-shot",

  "Mega Peacock (3 Face)": "peacock",
  "Bada Peacock (5 Face)": "bada-peacock",
  "Magic Peacock": "flower-pots-asoka-1-box",
  "Bada Peacock": "bada-peacock",
  "Rotate Sparklers": "rotating-sparkler-gold",
  "Colour Koti": "flower-pots-colour-kotti-1-box",
  "Tin Colour Fountain": "multicolour-tin-fountain",
  Butterfly: "colour-change-butterfly",
  "Mega Siren": "siren-3-pcs-big",
  "Naya Falls": "4-out-3-piece",

  "Hitler (¼ Kg)": "super-bullet-bomb",
  "Hydro Bomb": "hydro-bomb-green",
  "Classic Bomb": "classic-bomb",
  "Digital Bomb": "digital-bomb",
  "Paper Bomb (¼ Kg)": "1-kg-paper-bomb",
  "Paper Bomb (½ Kg)": "1%c2%bd-kg-paper-bomb",
  "Paper Bomb (1 Kg)": "1-kg-paper-bomb-2",

  "3¼ Lakshmi (1 Packet)": "3%c2%bd-lakshmi-1-pkt",
  "Gold Lakshmi (1 Packet)": "4-super-deluxe-1-pkt",
  "4 DLX Lakshmi": "4-lakshmi-deluxe-1-pkt",
  "Hulk DLX": "4-mega-deluxe-1-pkt",
  '5" Lion (1 Packet)': "55-kubera-1-pkt",
  "Red Bijili (100)": "red-bijili-1-bag",
  "Kaki Ola Vedi (1 Packet)": "two-sound-3%c2%bd-1-pkt",
  "Jallikattu DLX (1 Packet)": "4-mega-deluxe-1-pkt",

  "Roll Cap": "peacock-roll-caps",
  "Wonder Throw Box": "kit-kat",
  "Sky Lander (1 Piece)": "mega-rocket-6-high-flying-rockets",
  "Pop Pop (50 Boxes)": "asarafi-pops",
  "Bidi Blast (10 Boxes)": "electric-stones",
  "Gun with 3 Ring Caps": "hero-gun",
  "Ring Cap (100 Packets)": "peacock-roll-caps",
  "Anaconda (10 Boxes)": "snake-cartoon-big-1-box",

  "28 Wala": "28-deluxe",
  "100 Wala": "100-wala-1-pce",
  "200 Wala": "200-wala-1-pce",
  "24 DLX Wala": "24-deluxe",
  "1000 Wala": "1000-wala-1-pce",
  "2000 Wala": "2000-wala-1-pce",
  "5000 Wala": "5000-wala-1-pce",
  "10000 Wala": "10000-wala-1-pce",

  "10 Crackling": "1%c2%bd-twinkling-stars",
  "2¾ Kuruvi": "2%c2%be-kuruvi-1-pkt",
};
