// Product pack photos from SRK price-list image set (14 Jul 2026).
export const PRODUCT_IMAGES: Record<string, string> = {
  "1½ Twinkling Star": "/products/photos/1-5-twinkling-star.png",
  "Flower Pot Asoka": "/products/photos/flower-pot-asoka.png",
  "5 inch Fancy 2 in 1": "/products/photos/5-inch-fancy-2-in-1.png",
  "2 inch Double Ball": "/products/photos/2-inch-double-ball.png",
  "30 Shots Multi Colour": "/products/photos/30-shots-multi-colour.png",
  "12 Shots": "/products/photos/12-shots.png",
  "7 Shots": "/products/photos/7-shots.png",
  "Magic Peacock": "/products/photos/magic-peacock.png",
  "Colour Koti": "/products/photos/colour-koti.png",
  "Naya Falls": "/products/photos/naya-falls.png",
  "Bullet Bomb": "/products/photos/bullet-bomb.png",
  "Hydro Bomb": "/products/photos/hydro-bomb.png",
  "Classic Bomb": "/products/photos/classic-bomb.png",
  "Digital Bomb": "/products/photos/digital-bomb.png",
  "3¼ Lakshmi (1 Packet)": "/products/photos/3-25-lakshmi-1-packet.png",
  "Gold Lakshmi (1 Packet)": "/products/photos/gold-lakshmi-1-packet.png",
  "4 DLX Lakshmi": "/products/photos/4-dlx-lakshmi.png",
  "5\" Lion (1 Packet)": "/products/photos/5in-lion-1-packet.png",
  "Red Bijili (100)": "/products/photos/red-bijili-100.png",
  "Jallikattu DLX (1 Packet)": "/products/photos/jallikattu-dlx-1-packet.png",
  "2¾ Kuruvi": "/products/photos/2-75-kuruvi.png",
  "Roll Cap": "/products/photos/roll-cap.jpeg",
  "Wonder Throw Box": "/products/photos/wonder-throw-box.png",
  "Gun with 3 Ring Caps": "/products/photos/gun-with-3-ring-caps.png",
  "Ring Cap (100 Packets)": "/products/photos/ring-cap-100-packets.png",
  "Selfie Stick": "/products/photos/selfie-stick.png",
  "28 Wala": "/products/photos/28-wala.png",
  "100 Wala": "/products/photos/100-wala.png",
  "200 Wala": "/products/photos/200-wala.png",
  "24 DLX Wala": "/products/photos/24-dlx-wala.png",
  "1000 Wala": "/products/photos/1000-wala.png",
  "2000 Wala": "/products/photos/2000-wala.png",
  "5000 Wala": "/products/photos/5000-wala.png",
  "10000 Wala": "/products/photos/10000-wala.png"
};
